### ISSUE TITLE
Max limit

### ISSUE THREAD

**Issue by rayaned** [lzehrung/coinmarketcap#2]
can I access to change CoinMarketCap.Options Max 100 to 1999 trouth nuget

**Comment by lzehrung** [comment]
Sorry the maximum response size is 100 tickers or listings as defined by CoinMarketCap:
https://coinmarketcap.com/api/#endpoint_listings
https://coinmarketcap.com/api/#endpoint_ticker

Please note that the Options.Limit class is for convenience; it's really just an integer. You could provide your own value instead of using Limit.Max.

Also note that the Public API this library wraps is being migrated to the free tier of the Professional API on December 4th. https://pro.coinmarketcap.com/
